version: "3.8"
services:
  app:
    build: ./container/php
    volumes:
      - ./laravel:/work

  web:
    image: nginx:1.18-alpine
    ports:
      - 10080:80
    volumes:
      - ./laravel:/work
      - ./container/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work

  db:
    build: ./container/mysql
    volumes:
      - db-store:/var/lib/mysql

volumes:
  db-store:
